version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/ml"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      pip-all:
        patterns:
          - "*"
